FROM osrf/ros:jazzy-desktop

RUN apt-get update && apt-get install -y \
    ros-jazzy-ros-gz \
    ros-jazzy-turtlebot3* \
    ros-jazzy-realsense2-camera \
    python3-pip \
 && rm -rf /var/lib/apt/lists/*